# Generated by Django 3.1.14 on 2024-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20240102_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='description', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
